sudoku: fix borders
Fixes python traceback printed to terminal that ends with:
TypeError: 'Color' object does not support indexing

Fixes: https://bugzilla.gnome.org/show_bug.cgi?id=658519